### PR TITLE
Fix GHC 8.0.2 build

### PR DESCRIPTION
**Pull request by RyanGlScott**
This library fails to build with GHC 8.0.2 because it mistakenly doesn't annotate the overlapping `Monoid Point` instance with an `OVERLAPPING` annotation (8.0.2 is more strict about this than previous versions, see https://ghc.haskell.org/trac/ghc/ticket/12881). Luckily, it's easy to fix.

### CODE REVIEW

**Comment by fosskers** [comment]
Forgive me for not addressing this sooner, I hadn't noticed the PR.

I guess I never noticed this problem because there are no Stackage snapshots that use `8.0.2` yet. What's your dev setup?

**Comment by RyanGlScott** [comment]
Right, this was done by taking a Stackage LTS that uses GHC 8.0.1 and building everything with GHC 8.0.2-rc1 instead.

If you want to see the error message you'd get when building this package with GHC 8.0.2:

```
$ cabal install -w /opt/ghc/8.0.2/bin/ghc
Resolving dependencies...
Notice: installing into a sandbox located at
/home/rgscott/Documents/Hacking/Haskell/vectortiles-1.2.0/.cabal-sandbox
Configuring vectortiles-1.2.0...
Building vectortiles-1.2.0...
Failed to install vectortiles-1.2.0
Build log ( /home/rgscott/Documents/Hacking/Haskell/vectortiles-1.2.0/.cabal-sandbox/logs/vectortiles-1.2.0.log ):
cabal: Entering directory '.'
Configuring vectortiles-1.2.0...
Building vectortiles-1.2.0...
Preprocessing library vectortiles-1.2.0...
[1 of 6] Compiling Geography.VectorTile.Util ( Geography/VectorTile/Util.hs, dist/dist-sandbox-94ca564a/build/Geography/VectorTile/Util.o )
[2 of 6] Compiling Geography.VectorTile.Geometry ( Geography/VectorTile/Geometry.hs, dist/dist-sandbox-94ca564a/build/Geography/VectorTile/Geometry.o )

Geography/VectorTile/Geometry.hs:43:10: error:
    • Overlapping instances for Monoid Point
        arising from a use of ‘GHC.Base.$dmmconcat’
      Matching instances:
        instance (Monoid a, Monoid b) => Monoid (a, b)
          -- Defined in ‘GHC.Base’
        instance Monoid Point
          -- Defined at Geography/VectorTile/Geometry.hs:43:10
    • In the expression: GHC.Base.$dmmconcat @Point
      In an equation for ‘mconcat’: mconcat = GHC.Base.$dmmconcat @Point
      In the instance declaration for ‘Monoid Point’
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
vectortiles-1.2.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by fosskers** [comment]
Hm, given that the `(Monoid a, Monoid b) => Monoid (a, b)` instance already exists in `base` for `8.0.1`, I can probably kill the `Monoid Point` instance altogether to avoid confusion.

**Comment by fosskers** [comment]
http://hackage.haskell.org/package/vectortiles-1.2.0.1

^ This should fix it.

**Comment by RyanGlScott** [comment]
Thanks! Everything in `vectortiles-1.2.0.1` builds with GHC 8.0.2.

**Comment by fosskers** [comment]
Awesome, thanks for bringing this to my attention. Are you using `vectortiles` for a project?

**Comment by RyanGlScott** [comment]
Not for a project, no. I discovered this when doing a "smoke test" with GHC 8.0.2-rc1 on Stackage to find out if any packages compiled with 8.0.1 but not with 8.0.2 (which turned out to be the case, surprisingly). https://ghc.haskell.org/trac/ghc/ticket/12881 lists some other packages that were affected by the same issue.

**Comment by fosskers** [comment]
Neat, thanks for taking that upon yourself.
